deps: downgrade opencontainers/cgroups v0.0.6 to v0.0.3
The previous 'go get -u ./...' upgraded github.com/opencontainers/cgroups
from v0.0.3 to v0.0.6. This introduced a breaking API change:
Resources.PidsLimit changed from int64 to *int64 between those versions.

However, the vendored k8s.io/kubernetes v1.35.3 code in
cgroup_manager_linux.go:307 dereferences resourceConfig.PidsLimit
(*int64 -> int64) and assigns it to resources.PidsLimit, expecting
it to be int64 (as in cgroups v0.0.3). With cgroups v0.0.6, the
destination field is *int64, causing a compilation error:

    cannot use *resourceConfig.PidsLimit (variable of type int64)
    as *int64 value in assignment

k8s.io/kubernetes v1.35.3 was built against opencontainers/cgroups
v0.0.3 (confirmed via go mod graph). The fix is to downgrade
opencontainers/cgroups back to v0.0.3 to match what k8s expects.
This also downgrades google/cadvisor from v0.56.2 to v0.53.0,
which is likewise the version k8s v1.35.3 requires.

The broader lesson is that 'go get -u ./...' can upgrade transitive
dependencies beyond what direct dependencies are compatible with,
and should not be used indiscriminately.